### PR TITLE
Expose all SplashAttention tunable parameters in the workload.

### PR DESCRIPTION
**Pull request by vanbasten23**
Full tunable parameters for SplashAttention are [here](https://github.com/jax-ml/jax/blob/0181cb396d9956ea96f1d1de9695ceecdb1c7c5e/jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_kernel.py#L472-L497)

Test plan: $ python3 MaxText/train.py MaxText/configs/base.yml   run_name=$YOUR_JOB_NAME   base_output_directory=gs://xiowei-bucket-ctmd   dataset_type=synthetic   steps=10

cc: @miladm

### CODE REVIEW

**Review by Obliviour — COMMENTED** [review]
Can someone show me why it is important to expose all the SplashAttention parameters independently? 

We talked with Sharad early on and took his recommendation of tuning the flags in three blocks. So my current understanding is that is all that is needed to tune splash attention.

cc @gobbleturk @khatwanimohit

**Comment by vanbasten23** [comment]
> Can someone show me why it is important to expose all the SplashAttention parameters independently?
> 
> We talked with Sharad early on and took his recommendation of tuning the flags in three blocks. So my current understanding is that is all that is needed to tune splash attention.
> 
> cc @gobbleturk @khatwanimohit

Thanks for the info. This PR is result from an initiative to tune SplashAttention Pallas kernel with model parameters using MaxText and RayTune on Trillium, to demonstrate the Trillium capability before its GA. One of the steps is to expose a full set of SplashAttention tunable parameters in MaxText.

Let me check with Sharad to see if it's worthwhile to expose all tunable parameters.

**Review by gobbleturk — APPROVED** [review]
LGTM, thank you!

**Comment by vanbasten23** [comment]
> > Can someone show me why it is important to expose all the SplashAttention parameters independently?
> > We talked with Sharad early on and took his recommendation of tuning the flags in three blocks. So my current understanding is that is all that is needed to tune splash attention.
> > cc @gobbleturk @khatwanimohit
> 
> Thanks for the info. This PR is result from an initiative to tune SplashAttention Pallas kernel with model parameters using MaxText and RayTune on Trillium, to demonstrate the Trillium capability before its GA. One of the steps is to expose a full set of SplashAttention tunable parameters in MaxText.
> 
> Let me check with Sharad to see if it's worthwhile to expose all tunable parameters.

Got the [response](https://gist.github.com/vanbasten23/947496c9e095475035c5da588cd97542) and comment it here for future reference. It seems we can still play with some other parameters such as q/k/v_layout. So it may be worth to do it.

**Pull request merged**
